// Single source of truth for the industry list used in the application form.
// `value` is the English label sent to the CRM so records stay consistent regardless of the visitor's language.

export type Industry = {
  value: string;
  en: string;
  es: string;
  fr: string;
};

export const HERO_INDUSTRY_TO_LABEL: Record<string, string> = {
  construction: 'Construction',
  trucking: 'Trucking',
  restaurant: 'Restaurant',
};

export const INDUSTRIES: Industry[] = [
  { value: 'Accounting', en: 'Accounting', es: 'Contabilidad', fr: 'Comptabilité' },
  { value: 'Agriculture', en: 'Agriculture', es: 'Agricultura', fr: 'Agriculture' },
  { value: 'Air conditioning and HVAC', en: 'Air conditioning and HVAC', es: 'Aire acondicionado y HVAC', fr: 'Climatisation et CVC' },
  { value: 'Auto body and collision repair', en: 'Auto body and collision repair', es: 'Hojalatería y pintura de autos', fr: 'Carrosserie automobile' },
  { value: 'Auto dealership', en: 'Auto dealership', es: 'Venta de autos', fr: 'Concession automobile' },
  { value: 'Auto repair', en: 'Auto repair', es: 'Taller mecánico', fr: 'Réparation automobile' },
  { value: 'Bakery', en: 'Bakery', es: 'Panadería', fr: 'Boulangerie' },
  { value: 'Bar and nightclub', en: 'Bar and nightclub', es: 'Bar y discoteca', fr: 'Bar et discothèque' },
  { value: 'Barbershop and salon', en: 'Barbershop and salon', es: 'Barbería y salón de belleza', fr: 'Salon de coiffure et de beauté' },
  { value: 'Beverage distribution', en: 'Beverage distribution', es: 'Distribución de bebidas', fr: 'Distribution de boissons' },
  { value: 'Bakery equipment', en: 'Bakery equipment', es: 'Equipo de panadería', fr: 'Équipement de boulangerie' },
  { value: 'Boat and marine', en: 'Boat and marine', es: 'Botes y náutica', fr: 'Bateaux et marine' },
  { value: 'Bookkeeping', en: 'Bookkeeping', es: 'Teneduría de libros', fr: 'Tenue de livres' },
  { value: 'Brewery and winery', en: 'Brewery and winery', es: 'Cervecería y vinícola', fr: 'Brasserie et vignoble' },
  { value: 'Butcher shop', en: 'Butcher shop', es: 'Carnicería', fr: 'Boucherie' },
  { value: 'Cabinet making and millwork', en: 'Cabinet making and millwork', es: 'Fabricación de gabinetes', fr: "Fabrication d'armoires" },
  { value: 'Car wash', en: 'Car wash', es: 'Lavado de autos', fr: 'Lave-auto' },
  { value: 'Carpentry', en: 'Carpentry', es: 'Carpintería', fr: 'Menuiserie' },
  { value: 'Catering', en: 'Catering', es: 'Servicio de banquetes', fr: 'Traiteur' },
  { value: 'Childcare and daycare', en: 'Childcare and daycare', es: 'Guardería infantil', fr: "Garderie d'enfants" },
  { value: 'Cleaning and janitorial services', en: 'Cleaning and janitorial services', es: 'Limpieza y servicios de conserjería', fr: 'Nettoyage et conciergerie' },
  { value: 'Coffee shop', en: 'Coffee shop', es: 'Cafetería', fr: 'Café' },
  { value: 'Concrete and masonry', en: 'Concrete and masonry', es: 'Concreto y mampostería', fr: 'Béton et maçonnerie' },
  { value: 'Construction', en: 'Construction', es: 'Construcción', fr: 'Construction' },
  { value: 'Consulting', en: 'Consulting', es: 'Consultoría', fr: 'Conseil' },
  { value: 'Convenience store', en: 'Convenience store', es: 'Tienda de conveniencia', fr: 'Dépanneur' },
  { value: 'Courier and delivery services', en: 'Courier and delivery services', es: 'Mensajería y entregas', fr: 'Messagerie et livraison' },
  { value: 'Crane and rigging', en: 'Crane and rigging', es: 'Grúas y aparejos', fr: 'Grues et gréage' },
  { value: 'Daycare center', en: 'Daycare center', es: 'Centro de cuidado infantil', fr: "Centre de la petite enfance" },
  { value: 'Demolition', en: 'Demolition', es: 'Demolición', fr: 'Démolition' },
  { value: 'Dental practice', en: 'Dental practice', es: 'Consultorio dental', fr: 'Cabinet dentaire' },
  { value: 'Dry cleaning and laundry', en: 'Dry cleaning and laundry', es: 'Tintorería y lavandería', fr: 'Nettoyage à sec et buanderie' },
  { value: 'E-commerce and online retail', en: 'E-commerce and online retail', es: 'Comercio en línea', fr: 'Commerce en ligne' },
  { value: 'Electrical contracting', en: 'Electrical contracting', es: 'Contratista eléctrico', fr: 'Entrepreneur électricien' },
  { value: 'Event planning and rentals', en: 'Event planning and rentals', es: 'Planeación de eventos y renta de equipo', fr: "Planification d'événements et location" },
  { value: 'Excavation and grading', en: 'Excavation and grading', es: 'Excavación y nivelación', fr: 'Excavation et nivellement' },
  { value: 'Farming and ranching', en: 'Farming and ranching', es: 'Agricultura y ganadería', fr: "Agriculture et élevage" },
  { value: 'Fencing contractor', en: 'Fencing contractor', es: 'Instalación de cercas', fr: 'Entrepreneur en clôtures' },
  { value: 'Fitness center and gym', en: 'Fitness center and gym', es: 'Gimnasio', fr: 'Centre de conditionnement physique' },
  { value: 'Flooring installation', en: 'Flooring installation', es: 'Instalación de pisos', fr: 'Installation de planchers' },
  { value: 'Florist', en: 'Florist', es: 'Florería', fr: 'Fleuriste' },
  { value: 'Food processing', en: 'Food processing', es: 'Procesamiento de alimentos', fr: "Transformation alimentaire" },
  { value: 'Food truck', en: 'Food truck', es: 'Camión de comida', fr: 'Camion de nourriture' },
  { value: 'Freight brokerage', en: 'Freight brokerage', es: 'Corretaje de carga', fr: 'Courtage de fret' },
  { value: 'Furniture manufacturing', en: 'Furniture manufacturing', es: 'Fabricación de muebles', fr: 'Fabrication de meubles' },
  { value: 'General contracting', en: 'General contracting', es: 'Contratista general', fr: 'Entrepreneur général' },
  { value: 'Grocery store', en: 'Grocery store', es: 'Tienda de abarrotes', fr: "Épicerie" },
  { value: 'Hair salon and barbershop', en: 'Hair salon and barbershop', es: 'Salón de belleza y barbería', fr: 'Salon de coiffure' },
  { value: 'Hardware store', en: 'Hardware store', es: 'Ferretería', fr: 'Quincaillerie' },
  { value: 'Home healthcare', en: 'Home healthcare', es: 'Cuidado de salud en el hogar', fr: 'Soins de santé à domicile' },
  { value: 'Home inspection', en: 'Home inspection', es: 'Inspección de viviendas', fr: 'Inspection de maisons' },
  { value: 'Hospitality and hotels', en: 'Hospitality and hotels', es: 'Hospitalidad y hoteles', fr: 'Hôtellerie' },
  { value: 'HVAC and refrigeration', en: 'HVAC and refrigeration', es: 'Climatización y refrigeración', fr: 'CVC et réfrigération' },
  { value: 'Import and export', en: 'Import and export', es: 'Importación y exportación', fr: 'Importation et exportation' },
  { value: 'Industrial equipment rental', en: 'Industrial equipment rental', es: 'Renta de equipo industrial', fr: 'Location d’équipement industriel' },
  { value: 'Insurance agency', en: 'Insurance agency', es: 'Agencia de seguros', fr: "Agence d'assurance" },
  { value: 'Interior design', en: 'Interior design', es: 'Diseño de interiores', fr: "Design d'intérieur" },
  { value: 'IT services and consulting', en: 'IT services and consulting', es: 'Servicios y consultoría de TI', fr: 'Services et conseil en TI' },
  { value: 'Janitorial services', en: 'Janitorial services', es: 'Servicios de limpieza', fr: 'Services de conciergerie' },
  { value: 'Jewelry manufacturing and repair', en: 'Jewelry manufacturing and repair', es: 'Fabricación y reparación de joyería', fr: 'Fabrication et réparation de bijoux' },
  { value: 'Landscaping', en: 'Landscaping', es: 'Jardinería y paisajismo', fr: 'Aménagement paysager' },
  { value: 'Laundromat', en: 'Laundromat', es: 'Lavandería automática', fr: 'Buanderie libre-service' },
  { value: 'Legal services', en: 'Legal services', es: 'Servicios legales', fr: 'Services juridiques' },
  { value: 'Limousine and chauffeur service', en: 'Limousine and chauffeur service', es: 'Servicio de limusina y chofer', fr: 'Service de limousine et chauffeur' },
  { value: 'Logging and forestry', en: 'Logging and forestry', es: 'Explotación forestal', fr: 'Exploitation forestière' },
  { value: 'Machine shop', en: 'Machine shop', es: 'Taller de maquinado', fr: 'Atelier d’usinage' },
  { value: 'Manufacturing', en: 'Manufacturing', es: 'Manufactura', fr: 'Fabrication' },
  { value: 'Marketing and advertising agency', en: 'Marketing and advertising agency', es: 'Agencia de mercadeo y publicidad', fr: 'Agence de marketing et publicité' },
  { value: 'Medical practice', en: 'Medical practice', es: 'Consultorio médico', fr: 'Cabinet médical' },
  { value: 'Meat processing', en: 'Meat processing', es: 'Procesamiento de carnes', fr: 'Transformation de la viande' },
  { value: 'Metal fabrication', en: 'Metal fabrication', es: 'Fabricación de metales', fr: 'Fabrication métallique' },
  { value: 'Mining and quarrying', en: 'Mining and quarrying', es: 'Minería y canteras', fr: 'Exploitation minière et carrières' },
  { value: 'Mobile home and RV park', en: 'Mobile home and RV park', es: 'Parque de casas móviles y RV', fr: 'Parc de maisons mobiles et de VR' },
  { value: 'Moving and storage', en: 'Moving and storage', es: 'Mudanzas y almacenamiento', fr: 'Déménagement et entreposage' },
  { value: 'Nail salon', en: 'Nail salon', es: 'Salón de uñas', fr: 'Salon de manucure' },
  { value: 'Nursery and garden center', en: 'Nursery and garden center', es: 'Vivero y centro de jardinería', fr: 'Pépinière et centre de jardinage' },
  { value: 'Oil and gas services', en: 'Oil and gas services', es: 'Servicios de petróleo y gas', fr: 'Services pétroliers et gaziers' },
  { value: 'Painting contractor', en: 'Painting contractor', es: 'Contratista de pintura', fr: 'Entrepreneur en peinture' },
  { value: 'Paving and asphalt', en: 'Paving and asphalt', es: 'Pavimentación y asfalto', fr: 'Pavage et asphalte' },
  { value: 'Pest control', en: 'Pest control', es: 'Control de plagas', fr: 'Lutte antiparasitaire' },
  { value: 'Pet grooming and boarding', en: 'Pet grooming and boarding', es: 'Estética y hospedaje de mascotas', fr: "Toilettage et pension d'animaux" },
  { value: 'Pharmacy', en: 'Pharmacy', es: 'Farmacia', fr: 'Pharmacie' },
  { value: 'Photography and video production', en: 'Photography and video production', es: 'Fotografía y producción de video', fr: 'Photographie et production vidéo' },
  { value: 'Physical therapy clinic', en: 'Physical therapy clinic', es: 'Clínica de fisioterapia', fr: 'Clinique de physiothérapie' },
  { value: 'Plumbing contractor', en: 'Plumbing contractor', es: 'Contratista de plomería', fr: 'Entrepreneur en plomberie' },
  { value: 'Print shop', en: 'Print shop', es: 'Imprenta', fr: 'Imprimerie' },
  { value: 'Produce distribution', en: 'Produce distribution', es: 'Distribución de productos agrícolas', fr: 'Distribution de produits agricoles' },
  { value: 'Property management', en: 'Property management', es: 'Administración de propiedades', fr: 'Gestion immobilière' },
  { value: 'Real estate', en: 'Real estate', es: 'Bienes raíces', fr: 'Immobilier' },
  { value: 'Recycling and scrap metal', en: 'Recycling and scrap metal', es: 'Reciclaje y chatarra', fr: 'Recyclage et ferraille' },
  { value: 'Refrigerated transport', en: 'Refrigerated transport', es: 'Transporte refrigerado', fr: 'Transport réfrigéré' },
  { value: 'Restaurant', en: 'Restaurant', es: 'Restaurante', fr: 'Restaurant' },
  { value: 'Retail store', en: 'Retail store', es: 'Tienda al por menor', fr: 'Commerce de détail' },
  { value: 'Roofing contractor', en: 'Roofing contractor', es: 'Contratista de techos', fr: 'Entrepreneur en toiture' },
  { value: 'Salon and spa', en: 'Salon and spa', es: 'Salón y spa', fr: 'Salon et spa' },
  { value: 'Sanitation and waste management', en: 'Sanitation and waste management', es: 'Saneamiento y manejo de desechos', fr: 'Assainissement et gestion des déchets' },
  { value: 'Sawmill and lumber', en: 'Sawmill and lumber', es: 'Aserradero y madera', fr: 'Scierie et bois' },
  { value: 'Scaffolding and rigging', en: 'Scaffolding and rigging', es: 'Andamios y aparejos', fr: "Échafaudage et gréage" },
  { value: 'School and education', en: 'School and education', es: 'Escuela y educación', fr: 'École et éducation' },
  { value: 'Security services', en: 'Security services', es: 'Servicios de seguridad', fr: 'Services de sécurité' },
  { value: 'Septic and excavation services', en: 'Septic and excavation services', es: 'Servicios sépticos y excavación', fr: "Services septiques et d'excavation" },
  { value: 'Sheet metal fabrication', en: 'Sheet metal fabrication', es: 'Fabricación de láminas metálicas', fr: 'Fabrication de tôlerie' },
  { value: 'Shipping and freight', en: 'Shipping and freight', es: 'Envíos y carga', fr: 'Expédition et fret' },
  { value: 'Signage and printing', en: 'Signage and printing', es: 'Rotulación e impresión', fr: 'Enseignes et impression' },
  { value: 'Skid steer and equipment rental', en: 'Skid steer and equipment rental', es: 'Renta de minicargadoras y equipo', fr: 'Location de chargeuses compactes' },
  { value: 'Snow removal', en: 'Snow removal', es: 'Remoción de nieve', fr: 'Déneigement' },
  { value: 'Solar installation', en: 'Solar installation', es: 'Instalación de paneles solares', fr: 'Installation solaire' },
  { value: 'Sporting goods and equipment', en: 'Sporting goods and equipment', es: 'Artículos y equipo deportivo', fr: 'Articles et équipement de sport' },
  { value: 'Staffing and recruiting agency', en: 'Staffing and recruiting agency', es: 'Agencia de personal y reclutamiento', fr: 'Agence de placement et de recrutement' },
  { value: 'Steel and metal supply', en: 'Steel and metal supply', es: 'Suministro de acero y metales', fr: "Approvisionnement en acier et métaux" },
  { value: 'Taxi and rideshare fleet', en: 'Taxi and rideshare fleet', es: 'Flota de taxis y transporte compartido', fr: 'Flotte de taxis et covoiturage' },
  { value: 'Tile and stone work', en: 'Tile and stone work', es: 'Trabajo en azulejos y piedra', fr: 'Travaux de carrelage et de pierre' },
  { value: 'Tire shop', en: 'Tire shop', es: 'Llantera', fr: 'Magasin de pneus' },
  { value: 'Tow truck operator', en: 'Tow truck operator', es: 'Operador de grúas de remolque', fr: 'Exploitant de dépanneuses' },
  { value: 'Towing and roadside assistance', en: 'Towing and roadside assistance', es: 'Remolque y asistencia en carretera', fr: 'Remorquage et assistance routière' },
  { value: 'Tree service', en: 'Tree service', es: 'Servicio de arbolado', fr: "Service d'arboriculture" },
  { value: 'Trucking', en: 'Trucking', es: 'Transporte de carga', fr: 'Camionnage' },
  { value: 'Upholstery', en: 'Upholstery', es: 'Tapicería', fr: 'Rembourrage' },
  { value: 'Used car sales', en: 'Used car sales', es: 'Venta de autos usados', fr: "Vente de voitures d'occasion" },
  { value: 'Vending machine services', en: 'Vending machine services', es: 'Servicios de máquinas expendedoras', fr: 'Services de distributeurs automatiques' },
  { value: 'Veterinary practice', en: 'Veterinary practice', es: 'Clínica veterinaria', fr: 'Clinique vétérinaire' },
  { value: 'Warehouse and distribution', en: 'Warehouse and distribution', es: 'Almacén y distribución', fr: 'Entreposage et distribution' },
  { value: 'Waste hauling', en: 'Waste hauling', es: 'Recolección de residuos', fr: 'Collecte des déchets' },
  { value: 'Water treatment', en: 'Water treatment', es: 'Tratamiento de agua', fr: "Traitement de l'eau" },
  { value: 'Welding services', en: 'Welding services', es: 'Servicios de soldadura', fr: 'Services de soudure' },
  { value: 'Wholesale distribution', en: 'Wholesale distribution', es: 'Distribución al por mayor', fr: 'Distribution en gros' },
  { value: 'Window and door installation', en: 'Window and door installation', es: 'Instalación de ventanas y puertas', fr: 'Installation de fenêtres et de portes' },
  { value: 'Woodworking and carpentry shop', en: 'Woodworking and carpentry shop', es: 'Taller de carpintería y ebanistería', fr: 'Atelier de menuiserie' },
  { value: 'Other', en: 'Other', es: 'Otro', fr: 'Autre' },
];
